### PR TITLE
Add DataLog

### PR DESCRIPTION
**Pull request by auscompgeek**

### CODE REVIEW

**Comment by auscompgeek** [comment]
I seem to be getting a compile error:
```
wpiutil/rpy-include/rpygen/wpi__log__RawLogEntry.hpp:15:10: fatal error: rpygen/wpi__log__DataLogEntry.hpp: No such file or directory
   15 | #include <rpygen/wpi__log__DataLogEntry.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by virtuald** [comment]
Fixed some things, but need to go to bed:

- example needs to be better
- need to provide a 'get' function for a record which figures out the right type for you
- py::make_iterator isn't handled by pybind11-stubgen, which is annoying

**Comment by PeterJohnson** [comment]
Note there’s a native Python DataLogReader implementation in the allwpilib repo that could be pulled in instead (and upstream PRs welcome to clean it up). https://github.com/wpilibsuite/allwpilib/blob/main/wpiutil/examples/printlog/datalog.py

**Comment by auscompgeek** [comment]
In that case I'm fine with leaving out bindings for it, @virtuald thoughts?

**Comment by virtuald** [comment]
The bindings I pushed work, they just need some refinement. I should be able to get to it tonight. I'd rather go this route so there's less we have to maintain.

**Comment by virtuald** [comment]
Regarding py::make_iterator's useless type declaration, see https://github.com/pybind/pybind11/issues/1585.

**Pull request merged**
